### ISSUE TITLE
Plugins folder is assumed to be case sensitive

### ISSUE THREAD

**Issue by Thaodan** [JuneStepp/OneLauncher#30]
OneLauncher assumes that the plugin folder is always `Plugins` while the game just takes any form of the work no matter the case.

**Comment by JeremyStepp** [comment]
It seems that the game doesn't care about the case of Music, ui, skins, or documents settings folders either. I believe that this is just because Windows files and folders are case-insensitive by default. (https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity) The best solution here may be to use [PureWindowsPath](https://docs.python.org/3/library/pathlib.html#pathlib.PureWindowsPath) from pathlib for all paths used in WINE. With type hints, it shouldn't be too confusing to do this.

**Comment by JeremyStepp** [comment]
PureWindowsPath doesn't interact with the file system for obvious reasons, so it wouldn't work. A while ago, I made a subclass of Path that transforms paths into any existing path ignoring case. I need to switch all paths used in WINE to this. Remember to convert `check_if_valid_game_folder` and all the places using it.
