### ISSUE TITLE
Missing from Plugins list

### ISSUE THREAD

**Issue by DreamsUnderStars** [JuneStepp/OneLauncher#34]
TitanBar by Duriel
https://lotrointerface.com/downloads/info1140-TitanBar.html

Songbook by Chiran
https://lotrointerface.com/downloads/info380-Songbook.html

Vital Self by Souru 
https://lotrointerface.com/downloads/info1149-VitalSelf.html

These don't show up on you plugins search tab. I had to use Plugin Compendium to download/install them.

**Comment by JuneStepp** [comment]
The only API I know of that LotroInterface provides is an XML feed of each account's favorited interfaces in the form `https://api.lotrointerface.com/fav/<account name>.xml`. Interfaces also need to be separated into the music, theme, and plugin types. Now that OneLauncher handles almost all interface author packaging weirdness and mistakes, this could be done automatically, but I don't feel like making a bot at the moment. Compendium also uses the favorites feed, but adds from comment requests instead of the site updates feed and requires a properly configured `.plugincompendium file`.

**Comment by txtsd** [comment]
Thanks for explaining!
