### ISSUE TITLE
E12 & E15 error messages

### ISSUE THREAD

**Issue by Samus4145** [JuneStepp/OneLauncher#41]
Getting E12 Error getting news when opening app, latest build, and E15 SSL Error occurred in HTTPS connection when trying ti log in

**Comment by poumeyrol** [comment]
Same here

**Comment by JuneStepp** [comment]
This is due to the game server certificates getting updated. Not an issue in the development version of OneLauncher, but older versions like the ones that currently have builds need to get the certificate file manually updated. 

I'll try to get a new build out, but **you can easily fix the problem on your own by:**
1. Going to your OneLauncher install folder. By default, it's `C:\Program Files\OneLauncher` on Windows and `~/OneLauncher` on Linux.
2. Within that folder, navigating to `build/certificates/` ex. `C:\Program Files\OneLauncher\build\certificates\`. In that folder should be a file called `ca_certs.pem`.
3. Download and unzip [ca_certs.zip](https://github.com/JuneStepp/OneLauncher/files/11268251/ca_certs.zip). Everything should work if you replace the existing `ca_certs.pem` file with the one from the zip you just downloaded.

**Comment by JuneStepp** [comment]
Fixed in https://github.com/JuneStepp/OneLauncher/releases/tag/v1.2.9

Thanks to both of you for bringing up the issue!
