### ISSUE TITLE
OneLauncher with Steam Client Won't Launch (Windows 11)

### ISSUE THREAD

**Issue by OKRD342** [JuneStepp/OneLauncher#64]
Hi. I was previously launching the old version of OneLauncher by including the line 
"C:\Program Files\OneLauncher\onelauncher.exe" %command%
under Launch Options on Steam for the LOTRO Steam client on Windows 11.

Since I upgraded to OneLauncher 2.0, OneLauncher won't start when I launch LOTRO on Steam. Does anyone know why this might be happening?

**Comment by JuneStepp** [comment]
Normally, Steam launch options are just passed to the game's executable. "%command%" gets replaced with the command to launch the game's executable; what normally comes before the launch options. 
So what you're actually doing is passing the official game launcher as an argument to OneLauncher. OneLauncher 2.0 is probably not starting, because it doesn't recognize that as a valid command line option.

I'd recommend [adding OneLauncher as a non-steam game](https://help.steampowered.com/en/faqs/view/4B8B-9697-2338-40EC) if you want to use it through Steam.

**Comment by OKRD342** [comment]
Thank you. I just decided to add OneLauncher as a non-Steam game.
